version: '2'
services:
  tf-20-gpu:
    container_name: tf-20-gpu
    image: hooyao/tensorflow-dev:20a_gpu
    ports:
      - "8888:8888"
      - "6006:6006"
    entrypoint: ["/bin/bash", "-c", "jupyter notebook --ip='*' --NotebookApp.token= --port=8888 --no-browser --allow-root"]
    volumes:
      - $HOME/DockerData/tensorflow:/root/pyprojects
