version: '2'
services:
  tf-cpu-36:
    container_name: tfcpu36
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "6006:6006"
    entrypoint: ["/bin/bash", "-c", "source activate tf-cpu-36 && jupyter notebook --ip='*' --NotebookApp.token= --port=8888 --no-browser --allow-root"]
    volumes:
      - $HOME/DockerData/tensorflow:/root/pyprojects
