version: '2'
services:
  tf-cpu-36:
    container_name: tfcpu36
    image: hooyao/tensorflow-dev:180_gpu
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - $HOME/DockerData/tensorflow:/root/pyprojects
