version: '2'
services:
  tf2_gpu:
    container_name: tf2_${IMG_TAG}
    image: hooyao/tensorflow-dev:${IMG_TAG}
    ports:
      - "8888:8888"
      - "6006:6006"
    entrypoint: ["/bin/bash", "-c", "jupyter notebook --ip='0.0.0.0' --NotebookApp.token= --port=8888 --no-browser --allow-root"]
    volumes:
      - $CUR_DIR:/root/pyprojects
